
server:
  port: 9004
  
spring:
  application:
    name: yzblog-sms
    
  redis:
    host: ENC(RWivxW0JRzbf97eKqhpK++dVSvMZFds2)
    port: 8080
    password:
    timeout: 5000ms
    
  rabbitmq:
    virtual-host: myrabbitmq
    host: ENC(PIS+LF8DRIas7LYrkxl/siDRkVA1lYpX)
    port: 5672
    username: ENC(VQW3MeUhcudI4+b/aREDRQ==)
    password: ENC(N4acvJ3W+OseCWZEfUnBbOwIcayrXZVp)


#是否激活 swagger true or false
swagger:
  is:
    enable: true
  scan-package: xyz.yzblog.sms.controller

service:
  appid: FGW1BATNiFJxgvnJ1Xl3VpE9X6hxMqSJ
  appkey: Wtu1QCWJfatj+y/TIlBoBMUKsHuzcEJzU0kgvhZSFOkd8Y4EmAwEp3TInjbsuykw
  templateid: s60i5lcCiOMZMTBr1PZwRQ==


