server:
  port: 9002
  
spring:
  application:
    name: yzblog-article
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: ENC(vZSAzPqDeMa6QyAfOnjsGw==)
    password: ENC(RCwKx2oAxjqnnKYPajABZCYTl0wff5JA)
    url: ENC(Jc7ZQpEHpcwBZOTNIi+YMjgiDeQZyJUPOUdcPlhHG9kdzY9JtlXKTcCJvu629NvV8PrzAIT/lSsouH9cJP1yp/DQMmvuv/TP6YuYoaGzv3dS+y/7rib/6A==)
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    generate-ddl: true 
  

#是否激活 swagger true or false
swagger:
  is:
    enable: true
  scan-package: xyz.yzblog.article.controller

jasypt:
  encryptor:
    password: yzblog

