
server:
  port: 9004
  
spring:
  application:
    name: yzblog-search
    
  data:
    elasticsearch:
      cluster-nodes: ENC(VdgQyQ9iamzO2zeB9x3yiJ8PWuuPCxeqAdAm/TGP5CI=)

#是否激活 swagger true or false
swagger:
  is:
    enable: true
  scan-package: xyz.yzblog.search.controller


